export const mockTemplates = [
  {
    id: '1',
    name: 'Modern Business',
    type: 'Multi-Page',
    style: 'Modern',
    pages: 5,
    preview: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    features: ['Responsive', 'SEO Optimized', 'Contact Forms'],
    isActive: true,
  },
  {
    id: '2',
    name: 'Minimal Portfolio',
    type: 'One Page',
    style: 'Minimal',
    pages: 1,
    preview: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    features: ['Clean Design', 'Portfolio Grid', 'Smooth Scrolling'],
    isActive: false,
  },
  {
    id: '3',
    name: 'Bold Agency',
    type: 'Landing Page',
    style: 'Bold',
    pages: 1,
    preview: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    features: ['Eye-catching', 'Conversion Focused', 'Video Background'],
    isActive: false,
  },
  {
    id: '4',
    name: 'Classic Corporate',
    type: 'Multi-Page',
    style: 'Classic',
    pages: 7,
    preview: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
    features: ['Professional', 'Multi-language', 'Blog Ready'],
    isActive: false,
  },
  {
    id: '5',
    name: 'Startup Launch',
    type: 'Landing Page',
    style: 'Modern',
    pages: 1,
    preview: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    features: ['Product Showcase', 'Pricing Tables', 'FAQ Section'],
    isActive: false,
  },
  {
    id: '6',
    name: 'Creative Studio',
    type: 'One Page',
    style: 'Bold',
    pages: 1,
    preview: 'linear-gradient(135deg, #30cfd0 0%, #330867 100%)',
    features: ['Portfolio', 'Team Section', 'Contact Form'],
    isActive: false,
  },
  {
    id: '7',
    name: 'Elegant Services',
    type: 'Multi-Page',
    style: 'Minimal',
    pages: 4,
    preview: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
    features: ['Service Pages', 'Booking System', 'Testimonials'],
    isActive: false,
  },
  {
    id: '8',
    name: 'Tech Product',
    type: 'Landing Page',
    style: 'Modern',
    pages: 1,
    preview: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)',
    features: ['Feature Highlights', 'Demo Section', 'CTA Focused'],
    isActive: false,
  },
  {
    id: '9',
    name: 'Restaurant',
    type: 'Multi-Page',
    style: 'Classic',
    pages: 6,
    preview: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
    features: ['Menu Display', 'Reservations', 'Gallery'],
    isActive: false,
  },
  {
    id: '10',
    name: 'Fitness Studio',
    type: 'One Page',
    style: 'Bold',
    pages: 1,
    preview: 'linear-gradient(135deg, #ff6e7f 0%, #bfe9ff 100%)',
    features: ['Class Schedule', 'Trainer Profiles', 'Membership'],
    isActive: false,
  },
  {
    id: '11',
    name: 'Consulting Firm',
    type: 'Multi-Page',
    style: 'Classic',
    pages: 5,
    preview: 'linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)',
    features: ['Case Studies', 'Team Bios', 'Blog'],
    isActive: false,
  },
  {
    id: '12',
    name: 'App Landing',
    type: 'Landing Page',
    style: 'Modern',
    pages: 1,
    preview: 'linear-gradient(135deg, #f77062 0%, #fe5196 100%)',
    features: ['App Showcase', 'Download Buttons', 'Features List'],
    isActive: false,
  },
];

export const mockPages = [
  {
    id: '1',
    name: 'Home',
    slug: '/home',
    status: 'published',
    isHomepage: true,
    lastEdited: '2024-02-28',
    sections: {
      hero: {
        heading: 'Welcome to Your Amazing Business',
        subheading: 'We provide exceptional services that help your business grow and succeed in the digital world.',
        ctaText: 'Get Started',
        ctaLink: '/contact',
        ctaStyle: 'primary',
        backgroundType: 'gradient',
        backgroundImage: '',
        textAlignment: 'center',
      },
      about: {
        title: 'About Us',
        body: 'We are a team of passionate professionals dedicated to delivering excellence. With over 10 years of experience, we have helped hundreds of businesses achieve their goals.',
        image: '/placeholder-about.jpg',
        imagePosition: 'right',
      },
      services: {
        title: 'Our Services',
        subtitle: 'What we offer to help you succeed',
        cards: [
          { icon: '💼', title: 'Consulting', description: 'Expert business consulting to drive growth' },
          { icon: '🎨', title: 'Design', description: 'Beautiful designs that capture your brand' },
          { icon: '⚙️', title: 'Development', description: 'Robust technical solutions built to scale' },
        ],
        cardsPerRow: 3,
      },
      testimonials: {
        show: true,
        items: [
          { name: 'John Smith', role: 'CEO, TechCorp', text: 'Outstanding service! Highly recommended.', avatar: '' },
          { name: 'Sarah Johnson', role: 'Founder, StartupX', text: 'They transformed our business completely.', avatar: '' },
        ],
      },
      contact: {
        phone: '+1 (555) 123-4567',
        email: 'hello@business.com',
        address: '123 Business St, Suite 100, City, State 12345',
        mapLink: '',
        showMap: false,
      },
      footer: {
        text: '© 2024 Your Business. All rights reserved.',
        showSocial: true,
      },
    },
  },
  {
    id: '2',
    name: 'About',
    slug: '/about',
    status: 'published',
    isHomepage: false,
    lastEdited: '2024-02-27',
    sections: {},
  },
  {
    id: '3',
    name: 'Services',
    slug: '/services',
    status: 'published',
    isHomepage: false,
    lastEdited: '2024-02-26',
    sections: {},
  },
  {
    id: '4',
    name: 'Contact',
    slug: '/contact',
    status: 'published',
    isHomepage: false,
    lastEdited: '2024-02-25',
    sections: {},
  },
  {
    id: '5',
    name: 'Blog',
    slug: '/blog',
    status: 'hidden',
    isHomepage: false,
    lastEdited: '2024-02-20',
    sections: {},
  },
];

export const mockMedia = [
  { id: '1', filename: 'hero-image.jpg', type: 'image', size: '2.4 MB', date: '2024-02-28', url: '/media/hero.jpg' },
  { id: '2', filename: 'about-us.jpg', type: 'image', size: '1.8 MB', date: '2024-02-27', url: '/media/about.jpg' },
  { id: '3', filename: 'team-photo.jpg', type: 'image', size: '3.2 MB', date: '2024-02-26', url: '/media/team.jpg' },
  { id: '4', filename: 'service-1.jpg', type: 'image', size: '1.5 MB', date: '2024-02-25', url: '/media/service1.jpg' },
  { id: '5', filename: 'service-2.jpg', type: 'image', size: '1.7 MB', date: '2024-02-24', url: '/media/service2.jpg' },
  { id: '6', filename: 'logo.png', type: 'image', size: '245 KB', date: '2024-02-23', url: '/media/logo.png' },
  { id: '7', filename: 'banner.jpg', type: 'image', size: '2.9 MB', date: '2024-02-22', url: '/media/banner.jpg' },
  { id: '8', filename: 'product.jpg', type: 'image', size: '1.2 MB', date: '2024-02-21', url: '/media/product.jpg' },
  { id: '9', filename: 'brochure.pdf', type: 'document', size: '4.5 MB', date: '2024-02-20', url: '/media/brochure.pdf' },
  { id: '10', filename: 'testimonial-bg.jpg', type: 'image', size: '2.1 MB', date: '2024-02-19', url: '/media/testimonial.jpg' },
];

export const mockLeads = [
  {
    id: '1',
    name: 'Michael Chen',
    email: 'michael.chen@email.com',
    phone: '+1 (555) 234-5678',
    message: 'Interested in your consulting services. Please contact me to discuss.',
    date: '2024-02-28',
    status: 'new',
  },
  {
    id: '2',
    name: 'Emily Rodriguez',
    email: 'emily.r@company.com',
    phone: '+1 (555) 345-6789',
    message: 'Looking for a quote on web development project.',
    date: '2024-02-27',
    status: 'read',
  },
  {
    id: '3',
    name: 'David Thompson',
    email: 'david.t@business.com',
    phone: '+1 (555) 456-7890',
    message: 'Want to schedule a consultation call for next week.',
    date: '2024-02-26',
    status: 'read',
  },
  {
    id: '4',
    name: 'Lisa Wang',
    email: 'lisa.wang@startup.com',
    phone: '+1 (555) 567-8901',
    message: 'Interested in your design services. Can we meet?',
    date: '2024-02-25',
    status: 'new',
  },
  {
    id: '5',
    name: 'James Wilson',
    email: 'j.wilson@corp.com',
    phone: '+1 (555) 678-9012',
    message: 'Need help with digital marketing strategy.',
    date: '2024-02-24',
    status: 'read',
  },
  {
    id: '6',
    name: 'Amanda Foster',
    email: 'amanda@company.com',
    phone: '+1 (555) 789-0123',
    message: 'Question about your pricing packages.',
    date: '2024-02-23',
    status: 'read',
  },
  {
    id: '7',
    name: 'Robert Martinez',
    email: 'robert.m@email.com',
    phone: '+1 (555) 890-1234',
    message: 'Would like to partner with your agency.',
    date: '2024-02-22',
    status: 'new',
  },
  {
    id: '8',
    name: 'Jennifer Lee',
    email: 'jlee@business.com',
    phone: '+1 (555) 901-2345',
    message: 'Requesting information about your services.',
    date: '2024-02-21',
    status: 'read',
  },
];

export const mockClientAccount = {
  id: '1',
  name: 'John Anderson',
  email: 'john@clientbusiness.com',
  lastLogin: '2024-02-27 14:32',
  status: 'active',
  permissions: {
    editHero: true,
    editAbout: true,
    editServices: true,
    editContact: true,
    editSocialLinks: true,
    editColors: false,
    editFonts: false,
    addDeletePages: false,
    changeTemplate: false,
    accessMedia: false,
    viewSEO: false,
  },
};

export const mockSiteSettings = {
  general: {
    siteName: 'Your Business Name',
    tagline: 'Excellence in Everything We Do',
    logo: '/logo.png',
    favicon: '/favicon.ico',
    language: 'en',
  },
  design: {
    primaryColor: '#6366f1',
    secondaryColor: '#8b5cf6',
    fontFamily: 'Inter',
    fontSize: 'medium',
    borderRadius: 'rounded',
  },
  seo: {
    metaTitle: 'Your Business - Excellence in Everything',
    metaDescription: 'Leading provider of business solutions with over 10 years of experience.',
    keywords: 'business, consulting, services, professional',
    ogImage: '/og-image.jpg',
    analyticsId: 'UA-XXXXXXXXX-X',
  },
  social: {
    facebook: 'https://facebook.com/yourbusiness',
    instagram: 'https://instagram.com/yourbusiness',
    twitter: 'https://twitter.com/yourbusiness',
    linkedin: 'https://linkedin.com/company/yourbusiness',
    whatsapp: '+15551234567',
    youtube: 'https://youtube.com/@yourbusiness',
  },
  advanced: {
    customCSS: '',
    customJS: '',
    headerScripts: '',
  },
};

export const mockNavigationMenu = [
  { id: '1', label: 'Home', link: '/', order: 1, parent: null },
  { id: '2', label: 'About', link: '/about', order: 2, parent: null },
  { id: '3', label: 'Services', link: '/services', order: 3, parent: null },
  { id: '4', label: 'Our Work', link: '/portfolio', order: 4, parent: '3' },
  { id: '5', label: 'Testimonials', link: '/testimonials', order: 5, parent: '3' },
  { id: '6', label: 'Contact', link: '/contact', order: 6, parent: null },
];

export const mockActivityLog = [
  { id: '1', action: 'Updated homepage hero section', user: 'Admin', date: '2024-02-28 15:45' },
  { id: '2', action: 'Changed primary color', user: 'Admin', date: '2024-02-28 14:30' },
  { id: '3', action: 'Added new service card', user: 'Admin', date: '2024-02-27 16:20' },
  { id: '4', action: 'Updated contact information', user: 'Client', date: '2024-02-27 11:15' },
  { id: '5', action: 'Published About page', user: 'Admin', date: '2024-02-26 09:00' },
];
